# Generated by Django 4.0.6 on 2022-08-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=500)),
                ('bank_code', models.CharField(max_length=500)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('withdrawal', 'Withdrawal'), ('deposit', 'Deposit')], max_length=200)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=30)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(max_length=400)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=200)),
                ('mode', models.CharField(choices=[('usdt', 'Usdt'), ('bank', 'Bank')], max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_balance', models.IntegerField(default=0.0)),
                ('wallet_address', models.CharField(max_length=500, null=True)),
                ('account_number', models.CharField(max_length=500, null=True)),
                ('account_name', models.CharField(max_length=500, null=True)),
                ('referral_balance', models.IntegerField(default=0.0)),
                ('investment_balance', models.IntegerField(default=0.0)),
                ('referral_count', models.IntegerField(default=0, null=True)),
                ('investment_progress', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
