# Generated by Django 4.0.1 on 2022-08-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_wallet_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_code',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
