# Generated by Django 4.0.4 on 2022-07-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='investment_balance',
            field=models.IntegerField(default=0.0),
        ),
    ]
