# Generated by Django 4.0.6 on 2022-07-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_wallet_investment_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mode',
            field=models.CharField(choices=[('usdt', 'Usdt'), ('bank', 'Bank')], default='null', max_length=200),
            preserve_default=False,
        ),
    ]
