# Generated by Django 4.0.6 on 2022-07-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_transaction_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
