# Generated by Django 4.0.6 on 2022-07-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_wallet_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='image',
        ),
        migrations.AddField(
            model_name='transaction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
