# Generated by Django 4.0.6 on 2022-07-30 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
        ('client', '0008_transaction_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='Active_investment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_investment', to='packages.packages'),
        ),
    ]
