# Generated by Django 4.0.6 on 2022-07-31 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=0, max_digits=200),
        ),
    ]
