# Generated by Django 4.0.6 on 2022-07-31 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_alter_wallet_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_balance',
            field=models.IntegerField(default=0.0),
        ),
    ]
