# Generated by Django 4.0.6 on 2022-07-31 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_alter_wallet_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='investment_balance',
            field=models.DecimalField(decimal_places=0, max_digits=200),
        ),
    ]
